export const DEFAULT_MAX_TOKENS = 32000

export const modelConfigPresets = [
  // ==================== 中国大陆主流大模型 ====================
  {
    name: 'DeepSeek',
    vendor: '深度求索 (DeepSeek)',
    iconKey: 'deepseek',
    iconText: 'DS',
    accent: '#1d63ff',
    baseUrl: 'https://api.deepseek.com',
    modelsUrl: 'https://api.deepseek.com/models',
    modelName: 'deepseek-chat',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'DeepSeek V3 / R1 旗舰模型',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'Qwen DashScope',
    vendor: '阿里云百炼 (Model Studio)',
    iconKey: 'qwen',
    iconText: 'QW',
    accent: '#ff6a00',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    modelsUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1/models',
    modelName: 'qwen-max',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '通义千问全能旗舰',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'Kimi',
    vendor: '月之暗面 (Moonshot AI)',
    iconKey: 'kimi',
    iconText: 'KM',
    accent: '#1c1f26',
    baseUrl: 'https://api.moonshot.cn/v1',
    modelsUrl: 'https://api.moonshot.cn/v1/models',
    modelName: 'moonshot-v1-128k',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'Kimi 长上下文旗舰模型',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'GLM BigModel',
    vendor: '智谱 AI (Zhipu AI)',
    iconKey: 'zhipu',
    iconText: 'GLM',
    accent: '#0c1b33',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    modelsUrl: 'https://open.bigmodel.cn/api/paas/v4/models',
    modelName: 'glm-4-plus',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'GLM-4+ 旗舰智能体模型',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'MiniMax',
    vendor: '稀宇科技 (MiniMax)',
    iconKey: 'minimax',
    iconText: 'MM',
    accent: '#f43f5e',
    baseUrl: 'https://api.minimax.chat/v1',
    modelsUrl: 'https://api.minimax.chat/v1/models',
    modelName: 'MiniMax-Text-01',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'MiniMax 万亿 MoE 旗舰大模型',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'Volcengine Ark',
    vendor: '字节跳动火山引擎 (Doubao)',
    iconKey: 'doubao',
    iconText: 'DB',
    accent: '#2563eb',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    modelsUrl: 'https://ark.cn-beijing.volces.com/api/v3/models',
    modelName: 'doubao-pro-128k',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '豆包 Pro 旗舰模型',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'Baidu Qianfan',
    vendor: '百度智能云千帆 (ERNIE)',
    iconKey: 'baidu',
    iconText: 'BD',
    accent: '#2932e1',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    modelsUrl: 'https://qianfan.baidubce.com/v2/models',
    modelName: 'ernie-4.0-turbo-128k',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '文心 4.0 Turbo 旗舰大模型',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'Tencent Hunyuan',
    vendor: '腾讯云 (Tencent Cloud)',
    iconKey: 'tencent',
    iconText: 'HY',
    accent: '#0052d9',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    modelsUrl: 'https://api.hunyuan.cloud.tencent.com/v1/models',
    modelName: 'hunyuan-turbos-latest',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '腾讯混元 TurboS 旗舰模型',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'StepFun',
    vendor: '阶跃星辰 (StepFun)',
    iconKey: 'stepfun',
    iconText: 'SF',
    accent: '#0a0f1d',
    baseUrl: 'https://api.stepfun.com/v1',
    modelsUrl: 'https://api.stepfun.com/v1/models',
    modelName: 'step-2-16k',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '阶跃星辰千亿级旗舰模型',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'Baichuan AI',
    vendor: '百川智能 (Baichuan)',
    iconKey: 'baichuan',
    iconText: 'BC',
    accent: '#ff5e00',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    modelsUrl: 'https://api.baichuan-ai.com/v1/models',
    modelName: 'Baichuan4-Air',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '百川大模型通用旗舰',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: '01.AI',
    vendor: '零一万物 (01.AI)',
    iconKey: 'lingyi',
    iconText: 'YI',
    accent: '#111827',
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    modelsUrl: 'https://api.lingyiwanwu.com/v1/models',
    modelName: 'yi-lightning',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'Yi-Lightning 极速高精旗舰',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'SenseTime',
    vendor: '商汤日日新 (SenseNova)',
    iconKey: 'sensetime',
    iconText: 'ST',
    accent: '#e11d48',
    baseUrl: 'https://api.sensenova.cn/compatible-mode/v1',
    modelsUrl: 'https://api.sensenova.cn/compatible-mode/v1/models',
    modelName: 'SenseChat-5.5',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '商汤日日新 5.5 大模型',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'iFlytek Spark',
    vendor: '科大讯飞 (iFlytek)',
    iconKey: 'spark',
    iconText: 'XF',
    accent: '#0066ff',
    baseUrl: 'https://spark-api-open.xf-yun.com/v1',
    modelsUrl: 'https://spark-api-open.xf-yun.com/v1/models',
    modelName: '4.0Ultra',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '讯飞星火认知大模型 4.0 Ultra',
    category: 'china',
    categoryLabel: '国内主流'
  },
  {
    name: 'InfiniGen',
    vendor: '无问芯穹 (Infinigence)',
    iconKey: 'infinigence',
    iconText: 'IG',
    accent: '#18181b',
    baseUrl: 'https://cloud.infini-ai.com/maas/v1',
    modelsUrl: 'https://cloud.infini-ai.com/maas/v1/models',
    modelName: 'deepseek-v3',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '无问智算多元算力 MaaS',
    category: 'china',
    categoryLabel: '国内主流'
  },

  // ==================== 国际主流大模型 ====================
  {
    name: 'OpenAI',
    vendor: 'OpenAI',
    iconKey: 'openai',
    iconText: 'OAI',
    accent: '#10a37f',
    baseUrl: 'https://api.openai.com/v1',
    modelsUrl: 'https://api.openai.com/v1/models',
    modelName: 'gpt-4o',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'OpenAI 官方旗舰多模态模型',
    category: 'global',
    categoryLabel: '国际前沿'
  },
  {
    name: 'Anthropic Claude',
    vendor: 'Anthropic',
    iconKey: 'anthropic',
    iconText: 'AN',
    accent: '#d97706',
    baseUrl: 'https://api.anthropic.com/v1',
    modelsUrl: 'https://api.anthropic.com/v1/models',
    modelName: 'claude-3-7-sonnet-20250219',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'Claude 3.7 混合推理旗舰',
    category: 'global',
    categoryLabel: '国际前沿'
  },
  {
    name: 'Google Gemini',
    vendor: 'Google AI',
    iconKey: 'google',
    iconText: 'G',
    accent: '#1a73e8',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    modelsUrl: 'https://generativelanguage.googleapis.com/v1beta/models',
    modelName: 'gemini-2.5-pro',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'Gemini OpenAI-compatible 协议',
    category: 'global',
    categoryLabel: '国际前沿'
  },
  {
    name: 'xAI',
    vendor: 'xAI',
    iconKey: 'xai',
    iconText: 'xAI',
    accent: '#020617',
    baseUrl: 'https://api.x.ai/v1',
    modelsUrl: 'https://api.x.ai/v1/models',
    modelName: 'grok-2-latest',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'Grok 旗舰模型',
    category: 'global',
    categoryLabel: '国际前沿'
  },
  {
    name: 'Mistral AI',
    vendor: 'Mistral AI',
    iconKey: 'mistral',
    iconText: 'MI',
    accent: '#ff7000',
    baseUrl: 'https://api.mistral.ai/v1',
    modelsUrl: 'https://api.mistral.ai/v1/models',
    modelName: 'mistral-large-latest',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'Mistral Large 旗舰模型',
    category: 'global',
    categoryLabel: '国际前沿'
  },
  {
    name: 'Perplexity',
    vendor: 'Perplexity',
    iconKey: 'perplexity',
    iconText: 'PX',
    accent: '#20b8cd',
    baseUrl: 'https://api.perplexity.ai',
    modelsUrl: 'https://api.perplexity.ai/v1/models',
    modelName: 'sonar-pro',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '实时联网搜索模型',
    category: 'global',
    categoryLabel: '国际前沿'
  },

  // ==================== 聚合平台与高性能云算力 ====================
  {
    name: 'SiliconFlow',
    vendor: '硅基流动 (SiliconFlow)',
    iconKey: 'siliconflow',
    iconText: 'SF',
    accent: '#16a34a',
    baseUrl: 'https://api.siliconflow.cn/v1',
    modelsUrl: 'https://api.siliconflow.cn/v1/models',
    modelName: 'deepseek-ai/DeepSeek-V3',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '高性价比模型加速平台',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'ModelScope',
    vendor: '阿里魔搭 (ModelScope)',
    iconKey: 'modelscope',
    iconText: 'MS',
    accent: '#0066ff',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    modelsUrl: 'https://api-inference.modelscope.cn/v1/models',
    modelName: 'Qwen/Qwen2.5-72B-Instruct',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '魔搭社区模型推理 API',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'OpenRouter',
    vendor: 'OpenRouter',
    iconKey: 'openrouter',
    iconText: 'OR',
    accent: '#111827',
    baseUrl: 'https://openrouter.ai/api/v1',
    modelsUrl: 'https://openrouter.ai/api/v1/models',
    modelName: 'openai/gpt-4o',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '全球统一模型路由网关',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'Groq',
    vendor: 'Groq LPU',
    iconKey: 'groq',
    iconText: 'GQ',
    accent: '#f97316',
    baseUrl: 'https://api.groq.com/openai/v1',
    modelsUrl: 'https://api.groq.com/openai/v1/models',
    modelName: 'llama-3.3-70b-versatile',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'LPU 超高速极低延迟推理',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'Together AI',
    vendor: 'Together AI',
    iconKey: 'together',
    iconText: 'TG',
    accent: '#7c3aed',
    baseUrl: 'https://api.together.xyz/v1',
    modelsUrl: 'https://api.together.xyz/v1/models',
    modelName: 'deepseek-ai/DeepSeek-V3',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '开源模型云端托管',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'Cerebras',
    vendor: 'Cerebras Systems',
    iconKey: 'cerebras',
    iconText: 'CB',
    accent: '#dc2626',
    baseUrl: 'https://api.cerebras.ai/v1',
    modelsUrl: 'https://api.cerebras.ai/v1/models',
    modelName: 'llama3.3-70b',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '晶圆级超算极速推理',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'Fireworks AI',
    vendor: 'Fireworks AI',
    iconKey: 'fireworks',
    iconText: 'FW',
    accent: '#ea580c',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    modelsUrl: 'https://api.fireworks.ai/inference/v1/models',
    modelName: 'accounts/fireworks/models/deepseek-v3',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'Serverless 高性能模型推理',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'NVIDIA NIM',
    vendor: 'NVIDIA',
    iconKey: 'nvidia',
    iconText: 'NV',
    accent: '#76b900',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    modelsUrl: 'https://integrate.api.nvidia.com/v1/models',
    modelName: 'meta/llama-3.3-70b-instruct',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '英伟达企业级微服务推理',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'Hugging Face',
    vendor: 'Hugging Face',
    iconKey: 'huggingface',
    iconText: 'HF',
    accent: '#f59e0b',
    baseUrl: 'https://router.huggingface.co/v1',
    modelsUrl: 'https://router.huggingface.co/v1/models',
    modelName: 'meta-llama/Llama-3.3-70B-Instruct',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'HF 统一推理路由服务',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'GitHub Models',
    vendor: 'GitHub',
    iconKey: 'github',
    iconText: 'GH',
    accent: '#24292f',
    baseUrl: 'https://models.github.ai/inference',
    modelsUrl: 'https://models.github.ai/inference/models',
    modelName: 'gpt-4o',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'GitHub 开发者模型中心',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'DeepInfra',
    vendor: 'DeepInfra',
    iconKey: 'deepinfra',
    iconText: 'DI',
    accent: '#2563eb',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    modelsUrl: 'https://api.deepinfra.com/v1/openai/models',
    modelName: 'deepseek-ai/DeepSeek-V3',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '低成本按需推理托管',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'SambaNova',
    vendor: 'SambaNova Cloud',
    iconKey: 'sambanova',
    iconText: 'SN',
    accent: '#be123c',
    baseUrl: 'https://api.sambanova.ai/v1',
    modelsUrl: 'https://api.sambanova.ai/v1/models',
    modelName: 'Meta-Llama-3.3-70B-Instruct',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: 'SambaNova SN40L 极速云推理',
    category: 'hub',
    categoryLabel: '聚合算力'
  },
  {
    name: 'Ollama (本地/局域网)',
    vendor: 'Ollama',
    iconKey: 'ollama',
    iconText: 'OL',
    accent: '#111827',
    baseUrl: 'http://localhost:11434/v1',
    modelsUrl: 'http://localhost:11434/v1/models',
    modelName: 'qwen2.5-coder:32b',
    maxTokens: DEFAULT_MAX_TOKENS,
    provider: 'openai_compatible',
    note: '本地开源大模型部署运行时',
    category: 'hub',
    categoryLabel: '本地/算力'
  }
]
