export const modelConfigPresets = [
  {
    name: 'OpenAI',
    vendor: 'OpenAI',
    iconText: 'OAI',
    accent: '#111827',
    baseUrl: 'https://api.openai.com/v1',
    modelsUrl: 'https://api.openai.com/v1/models',
    modelName: 'gpt-5.5',
    maxTokens: 128000,
    provider: 'openai_compatible',
    note: 'GPT-5.5 frontier model'
  },
  {
    name: 'DeepSeek',
    vendor: 'DeepSeek',
    iconText: 'DS',
    accent: '#2563eb',
    baseUrl: 'https://api.deepseek.com',
    modelsUrl: 'https://api.deepseek.com/models',
    modelName: 'deepseek-v4-pro',
    maxTokens: 393216,
    provider: 'openai_compatible',
    note: 'DeepSeek V4 Pro'
  },
  {
    name: 'Qwen DashScope',
    vendor: 'Alibaba Cloud Model Studio',
    iconText: 'QW',
    accent: '#ff6a00',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    modelsUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1/models',
    modelName: 'qwen3.7-max',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'Qwen3.7 flagship'
  },
  {
    name: 'Kimi',
    vendor: 'Moonshot AI',
    iconText: 'KM',
    accent: '#6d28d9',
    baseUrl: 'https://api.moonshot.ai/v1',
    modelsUrl: 'https://api.moonshot.ai/v1/models',
    modelName: 'kimi-k2.7-code',
    maxTokens: 131072,
    provider: 'openai_compatible',
    note: 'Kimi coding flagship'
  },
  {
    name: 'MiniMax',
    vendor: 'MiniMax',
    iconText: 'MM',
    accent: '#0f766e',
    baseUrl: 'https://api.minimax.io/v1',
    modelsUrl: 'https://api.minimax.io/v1/models',
    modelName: 'MiniMax-M3',
    maxTokens: 128000,
    provider: 'openai_compatible',
    note: 'M3 agentic coding model'
  },
  {
    name: 'GLM BigModel',
    vendor: 'Zhipu AI',
    iconText: 'GLM',
    accent: '#0891b2',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    modelsUrl: 'https://open.bigmodel.cn/api/paas/v4/models',
    modelName: 'glm-5.1',
    maxTokens: 128000,
    provider: 'openai_compatible',
    note: 'GLM long-horizon model'
  },
  {
    name: 'OpenRouter',
    vendor: 'OpenRouter',
    iconText: 'OR',
    accent: '#111827',
    baseUrl: 'https://openrouter.ai/api/v1',
    modelsUrl: 'https://openrouter.ai/api/v1/models',
    modelName: 'openai/gpt-5.5',
    maxTokens: 128000,
    provider: 'openai_compatible',
    note: 'Unified model router'
  },
  {
    name: 'xAI',
    vendor: 'xAI',
    iconText: 'xAI',
    accent: '#020617',
    baseUrl: 'https://api.x.ai/v1',
    modelsUrl: 'https://api.x.ai/v1/models',
    modelName: 'grok-4.3',
    maxTokens: 65536,
    provider: 'openai_compatible',
    note: 'Grok flagship'
  },
  {
    name: 'Google Gemini',
    vendor: 'Google AI',
    iconText: 'G',
    accent: '#1a73e8',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    modelsUrl: 'https://generativelanguage.googleapis.com/v1beta/models',
    modelName: 'gemini-3.5-flash',
    maxTokens: 65536,
    provider: 'openai_compatible',
    note: 'Gemini OpenAI-compatible'
  },
  {
    name: 'Mistral AI',
    vendor: 'Mistral AI',
    iconText: 'MI',
    accent: '#ff7000',
    baseUrl: 'https://api.mistral.ai/v1',
    modelsUrl: 'https://api.mistral.ai/v1/models',
    modelName: 'mistral-medium-latest',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'Frontier multimodal model'
  },
  {
    name: 'Groq',
    vendor: 'Groq',
    iconText: 'GQ',
    accent: '#f97316',
    baseUrl: 'https://api.groq.com/openai/v1',
    modelsUrl: 'https://api.groq.com/openai/v1/models',
    modelName: 'openai/gpt-oss-120b',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'Low-latency inference'
  },
  {
    name: 'Together AI',
    vendor: 'Together AI',
    iconText: 'TG',
    accent: '#7c3aed',
    baseUrl: 'https://api.together.xyz/v1',
    modelsUrl: 'https://api.together.xyz/v1/models',
    modelName: 'deepseek-ai/DeepSeek-V3.2',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'Open model hosting'
  },
  {
    name: 'Cerebras',
    vendor: 'Cerebras',
    iconText: 'CB',
    accent: '#dc2626',
    baseUrl: 'https://api.cerebras.ai/v1',
    modelsUrl: 'https://api.cerebras.ai/v1/models',
    modelName: 'qwen-3-coder-480b',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'High-speed inference'
  },
  {
    name: 'Fireworks AI',
    vendor: 'Fireworks AI',
    iconText: 'FW',
    accent: '#ea580c',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    modelsUrl: 'https://api.fireworks.ai/inference/v1/models',
    modelName: 'accounts/fireworks/models/deepseek-v3p2',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'Serverless model inference'
  },
  {
    name: 'NVIDIA NIM',
    vendor: 'NVIDIA',
    iconText: 'NV',
    accent: '#76b900',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    modelsUrl: 'https://integrate.api.nvidia.com/v1/models',
    modelName: 'nvidia/llama-3.3-nemotron-super-49b-v1',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'NVIDIA-hosted NIM'
  },
  {
    name: 'Hugging Face',
    vendor: 'Hugging Face',
    iconText: 'HF',
    accent: '#f59e0b',
    baseUrl: 'https://router.huggingface.co/v1',
    modelsUrl: 'https://router.huggingface.co/v1/models',
    modelName: 'openai/gpt-oss-120b',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'Inference Providers router'
  },
  {
    name: 'GitHub Models',
    vendor: 'GitHub',
    iconText: 'GH',
    accent: '#24292f',
    baseUrl: 'https://models.github.ai/inference',
    modelsUrl: 'https://models.github.ai/inference/models',
    modelName: 'openai/gpt-5',
    maxTokens: 128000,
    provider: 'openai_compatible',
    note: 'GitHub model catalog'
  },
  {
    name: 'DeepInfra',
    vendor: 'DeepInfra',
    iconText: 'DI',
    accent: '#2563eb',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    modelsUrl: 'https://api.deepinfra.com/v1/openai/models',
    modelName: 'deepseek-ai/DeepSeek-V3.2',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'OpenAI-compatible hosting'
  },
  {
    name: 'SiliconFlow',
    vendor: 'SiliconFlow',
    iconText: 'SF',
    accent: '#16a34a',
    baseUrl: 'https://api.siliconflow.cn/v1',
    modelsUrl: 'https://api.siliconflow.cn/v1/models',
    modelName: 'deepseek-ai/DeepSeek-V3.2',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'China-accessible router'
  },
  {
    name: 'Volcengine Ark',
    vendor: 'ByteDance Volcano Engine',
    iconText: 'DB',
    accent: '#2563eb',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    modelsUrl: 'https://ark.cn-beijing.volces.com/api/v3/models',
    modelName: 'doubao-seed-1-6-250615',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'Doubao flagship endpoint'
  },
  {
    name: 'Baidu Qianfan',
    vendor: 'Baidu AI Cloud',
    iconText: 'BD',
    accent: '#2932e1',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    modelsUrl: 'https://qianfan.baidubce.com/v2/models',
    modelName: 'ernie-4.5-turbo-128k',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'ERNIE compatible API'
  },
  {
    name: 'Tencent Hunyuan',
    vendor: 'Tencent Cloud',
    iconText: 'HY',
    accent: '#006eff',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    modelsUrl: 'https://api.hunyuan.cloud.tencent.com/v1/models',
    modelName: 'hunyuan-turbos-latest',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'Hunyuan Turbo alias'
  },
  {
    name: 'ModelScope',
    vendor: 'ModelScope',
    iconText: 'MS',
    accent: '#00a3ff',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    modelsUrl: 'https://api-inference.modelscope.cn/v1/models',
    modelName: 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'ModelScope inference API'
  },
  {
    name: 'SambaNova',
    vendor: 'SambaNova Cloud',
    iconText: 'SN',
    accent: '#be123c',
    baseUrl: 'https://api.sambanova.ai/v1',
    modelsUrl: 'https://api.sambanova.ai/v1/models',
    modelName: 'Meta-Llama-3.3-70B-Instruct',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'SambaNova Cloud'
  },
  {
    name: 'AI/ML API',
    vendor: 'AI/ML API',
    iconText: 'AI',
    accent: '#4f46e5',
    baseUrl: 'https://api.aimlapi.com/v1',
    modelsUrl: 'https://api.aimlapi.com/models',
    modelName: 'openai/gpt-5.5',
    maxTokens: 128000,
    provider: 'openai_compatible',
    note: 'Unified model provider'
  },
  {
    name: 'Perplexity',
    vendor: 'Perplexity',
    iconText: 'PX',
    accent: '#20b8cd',
    baseUrl: 'https://api.perplexity.ai',
    modelsUrl: 'https://api.perplexity.ai/v1/models',
    modelName: 'sonar-deep-research',
    maxTokens: 32768,
    provider: 'openai_compatible',
    note: 'Search-grounded models'
  }
]
